export const usageMetricCodes = [
  'operation.admin.testdatacleanup',
  'operation.admin.testdatacleanupbyids',
  'operation.alert.ack',
  'operation.alert.close',
  'operation.alert.silence',
  'operation.alertrouting.create',
  'operation.alertrouting.toggle',
  'operation.alertrouting.update',
  'operation.apikey.create',
  'operation.apikey.revoke',
  'operation.approval.approve',
  'operation.approval.batchapprove',
  'operation.approval.batchreject',
  'operation.approval.reject',
  'operation.auth.changepassword',
  'operation.auth.login',
  'operation.auth.logout',
  'operation.batchdayreplay.approve',
  'operation.batchdayreplay.cancel',
  'operation.batchdayreplay.submit',
  'operation.instance.cancel',
  'operation.instance.pause',
  'operation.instance.resume',
  'operation.instance.terminate',
  'operation.jobdefinition.batchpatch',
  'operation.jobdefinition.clone',
  'operation.jobdefinition.copy',
  'operation.jobdefinition.create',
  'operation.jobdefinition.patch',
  'operation.jobdefinition.update',
  'operation.outbox.cleanup',
  'operation.outbox.republish',
  'operation.partition.cancel',
  'operation.partition.retry',
  'operation.partition.retry_failed_shards',
  'operation.pipelinedefinition.create',
  'operation.pipelinedefinition.toggle',
  'operation.pipelinedefinition.update',
  'operation.scheduler.pauseall',
  'operation.scheduler.resumeall',
  'operation.shard_catalog.delete',
  'operation.shard_catalog.upsert',
  'operation.system.maintenance.update',
  'operation.tenant.activate',
  'operation.tenant.batchcreate',
  'operation.tenant.create',
  'operation.tenant.suspend',
  'operation.tenant.update',
  'operation.tenant_placement.delete',
  'operation.tenant_placement.upsert',
  'operation.user.create',
  'operation.user.disable',
  'operation.user.enable',
  'operation.user.resetpassword',
  'operation.user.update',
  'operation.workflowrun.cancel',
  'operation.workflowrun.pause',
  'operation.workflowrun.resume',
  'operation.workflowrun.skipnode',
  'operation.workflowrun.terminate',
] as const

const domainKeys: Record<string, string> = {
  admin: 'admin',
  alert: 'alert',
  alertrouting: 'alertRouting',
  apikey: 'apiKey',
  approval: 'approval',
  auth: 'auth',
  batchdayreplay: 'batchDayReplay',
  instance: 'instance',
  jobdefinition: 'jobDefinition',
  outbox: 'outbox',
  partition: 'partition',
  pipelinedefinition: 'pipelineDefinition',
  scheduler: 'scheduler',
  shard_catalog: 'shardCatalog',
  system: 'system',
  tenant: 'tenant',
  tenant_placement: 'tenantPlacement',
  user: 'user',
  workflowrun: 'workflowRun',
}

const actionKeys: Record<string, string> = {
  ack: 'ack',
  activate: 'activate',
  approve: 'approve',
  batchapprove: 'batchApprove',
  batchcreate: 'batchCreate',
  batchpatch: 'batchPatch',
  batchreject: 'batchReject',
  cancel: 'cancel',
  changepassword: 'changePassword',
  cleanup: 'cleanup',
  clone: 'clone',
  close: 'close',
  copy: 'copy',
  create: 'create',
  delete: 'delete',
  disable: 'disable',
  enable: 'enable',
  login: 'login',
  logout: 'logout',
  maintenance_update: 'maintenanceUpdate',
  patch: 'patch',
  pause: 'pause',
  pauseall: 'pauseAll',
  reject: 'reject',
  republish: 'republish',
  resetpassword: 'resetPassword',
  resume: 'resume',
  resumeall: 'resumeAll',
  retry: 'retry',
  retry_failed_shards: 'retryFailedShards',
  silence: 'silence',
  skipnode: 'skipNode',
  submit: 'submit',
  suspend: 'suspend',
  terminate: 'terminate',
  testdatacleanup: 'testDataCleanup',
  testdatacleanupbyids: 'testDataCleanupByIds',
  toggle: 'toggle',
  update: 'update',
  upsert: 'upsert',
}

type Translate = (key: string) => string

export function usageMetricLabel(code: string, t: Translate): string {
  const [, domain, ...actionParts] = code.split('.')
  const domainKey = domainKeys[domain]
  const actionKey = actionKeys[actionParts.join('_')]
  if (!domainKey || !actionKey) return code
  return `${t(`usageSummary.metricDomains.${domainKey}`)} / ${t(
    `usageSummary.metricActions.${actionKey}`,
  )}`
}
