#!/usr/bin/env node
import { cp, lstat, mkdir, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, join, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const frontendDocs = resolve(root, process.env.FRONTEND_DOCS_ROOT || 'docs')
const backendDocs = resolve(root, process.env.BACKEND_DOCS_ROOT || '../file-batch-system/docs')
const generated = join(root, 'tools', 'docs-bridge', 'frontend', 'content')
const marker = join(generated, '.docs-generated')

const contains = (parent, child) => child === parent || child.startsWith(`${parent}${sep}`)
if ([frontendDocs, backendDocs].some((source) => contains(source, generated) || contains(generated, source))) {
  throw new Error('Document source paths must not overlap the generated docs directory')
}

async function isFile(path) {
  return (await stat(path).catch(() => null))?.isFile() === true
}

if (!(await isFile(join(backendDocs, 'README.md')))) {
  throw new Error(`Backend docs are unavailable: ${backendDocs}. Set BACKEND_DOCS_ROOT to the docs directory.`)
}
if (!(await isFile(join(frontendDocs, 'README.md')))) {
  throw new Error(`Frontend docs are unavailable: ${frontendDocs}`)
}
if ((await stat(generated).catch(() => null)) && !(await isFile(marker))) {
  throw new Error(`Refusing to replace an unowned docs directory: ${generated}`)
}

await rm(generated, { recursive: true, force: true })
await mkdir(generated, { recursive: true })
await writeFile(marker, 'Generated by scripts/docs-prepare.mjs. Do not edit.\n')

const copyFilter = async (path) => {
  const name = path.split(sep).at(-1)
  if (name === '.DS_Store' || name === 'node_modules' || name === '.git' || name === '.vitepress') {
    return false
  }
  return !(await lstat(path)).isSymbolicLink()
}

await cp(backendDocs, join(generated, 'backend'), {
  recursive: true,
  force: true,
  filter: copyFilter,
})
await cp(frontendDocs, join(generated, 'frontend'), {
  recursive: true,
  force: true,
  filter: copyFilter,
})

await writeFile(
  join(generated, 'README.md'),
  `# 批量调度平台文档

前端使用指南与后端架构、运维文档共用一个文档站。源文件分别由各自仓库维护。

## 产品与前端

- [产品使用指南](./frontend/user-guide/README.md)
- [前端文档索引](./frontend/README.md)
- [前端运维手册](./frontend/runbook/README.md)

## 后端与平台

- [后端文档索引](./backend/README.md)
- [系统架构](./backend/architecture/README.md)
- [后端运维手册](./backend/runbook/README.md)
- [API 文档](./backend/api/README.md)
`,
)

console.log(`[docs-prepare] unified source ready: frontend=${frontendDocs}, backend=${backendDocs}`)
